# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4   
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 9.0.x
    - name: Install .NET MAUI
      run: dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore samples/Foo.Bar.SampleApp.Net9/Foo.Bar.SampleApp.Net9.csproj
    - name: Build
      run: dotnet build samples/Foo.Bar.SampleApp.Net9/Foo.Bar.SampleApp.Net9.csproj -c Release -f net9.0-android --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: ./**/*.apk
